# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\aboutWindow5.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutWindow(object):
    def setupUi(self, aboutWindow):
        aboutWindow.setObjectName("aboutWindow")
        aboutWindow.resize(700, 580)
        aboutWindow.setMinimumSize(QtCore.QSize(700, 580))
        aboutWindow.setMaximumSize(QtCore.QSize(700, 580))
        aboutWindow.setStyleSheet("background-color: rgb(244, 232, 157);")
        self.centralwidget = QtWidgets.QWidget(aboutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtSobre = QtWidgets.QPushButton(self.centralwidget)
        self.txtSobre.setGeometry(QtCore.QRect(40, 80, 621, 281))
        self.txtSobre.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(199, 255, 243);\n"
"    border: 4px solid;\n"
"    border-color: rgb(66, 133, 199);\n"
"}")
        self.txtSobre.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/textosobre2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.txtSobre.setIcon(icon)
        self.txtSobre.setIconSize(QtCore.QSize(600, 600))
        self.txtSobre.setObjectName("txtSobre")
        self.imgSpeakyNotes = QtWidgets.QLabel(self.centralwidget)
        self.imgSpeakyNotes.setGeometry(QtCore.QRect(210, 20, 211, 51))
        self.imgSpeakyNotes.setText("")
        self.imgSpeakyNotes.setPixmap(QtGui.QPixmap("images/speakynotes.png"))
        self.imgSpeakyNotes.setScaledContents(True)
        self.imgSpeakyNotes.setObjectName("imgSpeakyNotes")
        self.imgDesenvolvedores = QtWidgets.QLabel(self.centralwidget)
        self.imgDesenvolvedores.setGeometry(QtCore.QRect(70, 380, 191, 31))
        self.imgDesenvolvedores.setText("")
        self.imgDesenvolvedores.setPixmap(QtGui.QPixmap("images/desenvolvedores.png"))
        self.imgDesenvolvedores.setScaledContents(True)
        self.imgDesenvolvedores.setObjectName("imgDesenvolvedores")
        self.txtDesenvolvedores = QtWidgets.QLabel(self.centralwidget)
        self.txtDesenvolvedores.setGeometry(QtCore.QRect(60, 420, 201, 161))
        self.txtDesenvolvedores.setText("")
        self.txtDesenvolvedores.setPixmap(QtGui.QPixmap("images/textodesenvolvedores.png"))
        self.txtDesenvolvedores.setScaledContents(True)
        self.txtDesenvolvedores.setObjectName("txtDesenvolvedores")
        self.imgContato = QtWidgets.QLabel(self.centralwidget)
        self.imgContato.setGeometry(QtCore.QRect(450, 390, 111, 31))
        self.imgContato.setText("")
        self.imgContato.setPixmap(QtGui.QPixmap("images/contatos1.png"))
        self.imgContato.setScaledContents(True)
        self.imgContato.setObjectName("imgContato")
        self.aboutOk_Button = QtWidgets.QPushButton(self.centralwidget)
        self.aboutOk_Button.setGeometry(QtCore.QRect(10, 10, 111, 51))
        self.aboutOk_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aboutOk_Button.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(52, 190, 78);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(54, 215, 96);\n"
"}\n"
"")
        self.aboutOk_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/okay.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutOk_Button.setIcon(icon1)
        self.aboutOk_Button.setIconSize(QtCore.QSize(30, 30))
        self.aboutOk_Button.setObjectName("aboutOk_Button")
        self.logoSpeakyNotes = QtWidgets.QLabel(self.centralwidget)
        self.logoSpeakyNotes.setGeometry(QtCore.QRect(430, 10, 61, 61))
        self.logoSpeakyNotes.setText("")
        self.logoSpeakyNotes.setPixmap(QtGui.QPixmap("images/logo_speakynotes.png"))
        self.logoSpeakyNotes.setScaledContents(True)
        self.logoSpeakyNotes.setObjectName("logoSpeakyNotes")
        self.instaClarice = QtWidgets.QLabel(self.centralwidget)
        self.instaClarice.setGeometry(QtCore.QRect(370, 480, 121, 31))
        self.instaClarice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instaClarice.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.instaClarice.setObjectName("instaClarice")
        self.instaGrasielly = QtWidgets.QLabel(self.centralwidget)
        self.instaGrasielly.setGeometry(QtCore.QRect(370, 520, 121, 31))
        self.instaGrasielly.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instaGrasielly.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.instaGrasielly.setObjectName("instaGrasielly")
        self.instaJackson = QtWidgets.QLabel(self.centralwidget)
        self.instaJackson.setGeometry(QtCore.QRect(520, 480, 131, 31))
        self.instaJackson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instaJackson.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.instaJackson.setObjectName("instaJackson")
        self.instaDanilo = QtWidgets.QLabel(self.centralwidget)
        self.instaDanilo.setGeometry(QtCore.QRect(370, 440, 151, 31))
        self.instaDanilo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instaDanilo.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.instaDanilo.setObjectName("instaDanilo")
        self.instaRoberto = QtWidgets.QLabel(self.centralwidget)
        self.instaRoberto.setGeometry(QtCore.QRect(520, 440, 151, 31))
        self.instaRoberto.setMinimumSize(QtCore.QSize(145, 21))
        self.instaRoberto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instaRoberto.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.instaRoberto.setObjectName("instaRoberto")
        self.instaLara = QtWidgets.QLabel(self.centralwidget)
        self.instaLara.setGeometry(QtCore.QRect(520, 520, 141, 31))
        self.instaLara.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instaLara.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.instaLara.setObjectName("instaLara")
        self.imgInsta = QtWidgets.QLabel(self.centralwidget)
        self.imgInsta.setGeometry(QtCore.QRect(570, 390, 31, 31))
        self.imgInsta.setText("")
        self.imgInsta.setPixmap(QtGui.QPixmap("images/instaICON.png"))
        self.imgInsta.setScaledContents(True)
        self.imgInsta.setObjectName("imgInsta")
        aboutWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(aboutWindow)
        self.aboutOk_Button.clicked.connect(aboutWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(aboutWindow)

    def retranslateUi(self, aboutWindow):
        _translate = QtCore.QCoreApplication.translate
        aboutWindow.setWindowTitle(_translate("aboutWindow", "Sobre"))
        self.instaClarice.setText(_translate("aboutWindow", "<html><head/><body><p><a href=\"https://instagram.com/clariiemesq_?igshid=YmMyMTA2M2Y=\"><span style=\" font-size:10pt; text-decoration: underline; color:#000000;\">@clariiemesq_</span></a></p></body></html>"))
        self.instaGrasielly.setText(_translate("aboutWindow", "<html><head/><body><p><a href=\"https://instagram.com/grasielly_gr?igshid=YmMyMTA2M2Y=\"><span style=\" font-size:10pt; text-decoration: underline; color:#000000;\">@grasielly_gr</span></a></p></body></html>"))
        self.instaJackson.setText(_translate("aboutWindow", "<html><head/><body><p><a href=\"https://instagram.com/jacksonwbbr?igshid=YmMyMTA2M2Y=\"><span style=\" font-size:10pt; text-decoration: underline; color:#000000;\">@jacksonwbbr</span></a></p></body></html>"))
        self.instaDanilo.setText(_translate("aboutWindow", "<html><head/><body><p><a href=\"https://instagram.com/albertdaniloo?igshid=YmMyMTA2M2Y=\"><span style=\" font-size:10pt; text-decoration: underline; color:#000000;\">@albertdaniloo</span></a></p></body></html>"))
        self.instaRoberto.setText(_translate("aboutWindow", "<html><head/><body><p><a href=\"https://instagram.com/jose_robertoskb?igshid=YmMyMTA2M2Y=\"><span style=\" font-size:10pt; text-decoration: underline; color:#000000;\">@jose_robertoskb</span></a></p></body></html>"))
        self.instaLara.setText(_translate("aboutWindow", "<html><head/><body><p><a href=\"https://instagram.com/lara_rayssa07?igshid=YmMyMTA2M2Y=\"><span style=\" text-decoration: underline; color:#000000;\">@lara_rayssa07</span></a></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aboutWindow = QtWidgets.QMainWindow()
    ui = Ui_aboutWindow()
    ui.setupUi(aboutWindow)
    aboutWindow.show()
    sys.exit(app.exec_())
