# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notesWindow(object):
    def setupUi(self, notesWindow):
        notesWindow.setObjectName("notesWindow")
        notesWindow.resize(400, 446)
        notesWindow.setMinimumSize(QtCore.QSize(400, 446))
        notesWindow.setMaximumSize(QtCore.QSize(400, 446))
        self.centralwidget = QtWidgets.QWidget(notesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 131, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 280, 101, 31))
        self.label_2.setObjectName("label_2")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(50, 350, 131, 71))
        self.confirmButton.setObjectName("confirmButton")
        self.dateExpiration = QtWidgets.QComboBox(self.centralwidget)
        self.dateExpiration.setGeometry(QtCore.QRect(170, 280, 181, 31))
        self.dateExpiration.setObjectName("dateExpiration")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(220, 350, 131, 71))
        self.cancelButton.setObjectName("cancelButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 70, 301, 191))
        self.textEdit.setObjectName("textEdit")
        notesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(notesWindow)
        self.cancelButton.clicked.connect(notesWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(notesWindow)

    def retranslateUi(self, notesWindow):
        _translate = QtCore.QCoreApplication.translate
        notesWindow.setWindowTitle(_translate("notesWindow", "Adicionar Lembrete"))
        self.label.setText(_translate("notesWindow", "Conteúdo do Lembrete:"))
        self.label_2.setText(_translate("notesWindow", "Período de duração:"))
        self.confirmButton.setText(_translate("notesWindow", "Confirmar"))
        self.cancelButton.setText(_translate("notesWindow", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    notesWindow = QtWidgets.QMainWindow()
    ui = Ui_notesWindow()
    ui.setupUi(notesWindow)
    notesWindow.show()
    sys.exit(app.exec_())
