# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notesWindow(object):
    def setupUi(self, notesWindow):
        notesWindow.setObjectName("notesWindow")
        notesWindow.resize(480, 500)
        notesWindow.setMinimumSize(QtCore.QSize(480, 500))
        notesWindow.setMaximumSize(QtCore.QSize(480, 500))
        notesWindow.setStyleSheet("background-color: rgb(244, 232, 157);")
        self.centralwidget = QtWidgets.QWidget(notesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 271, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/conteúdo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 310, 211, 41))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/periododeduracao.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(40, 400, 161, 71))
        self.confirmButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(52, 190, 78);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(54, 215, 96);\n"
"}\n"
"")
        self.confirmButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/confirmar_addwindow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confirmButton.setIcon(icon)
        self.confirmButton.setIconSize(QtCore.QSize(100, 100))
        self.confirmButton.setObjectName("confirmButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 70, 391, 201))
        self.textEdit.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.textEdit.setObjectName("textEdit")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(270, 400, 161, 71))
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(246, 11, 56);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(250, 43, 59);\n"
"}\n"
"")
        self.cancelButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/cancelar_addwindow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon1)
        self.cancelButton.setIconSize(QtCore.QSize(90, 90))
        self.cancelButton.setObjectName("cancelButton")
        self.dateNumbers = QtWidgets.QSpinBox(self.centralwidget)
        self.dateNumbers.setGeometry(QtCore.QRect(290, 310, 141, 41))
        self.dateNumbers.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.dateNumbers.setMinimum(1)
        self.dateNumbers.setMaximum(30)
        self.dateNumbers.setObjectName("dateNumbers")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 10, 41, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/7830644_pencil_icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        notesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(notesWindow)
        self.cancelButton.clicked.connect(notesWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(notesWindow)

    def retranslateUi(self, notesWindow):
        _translate = QtCore.QCoreApplication.translate
        notesWindow.setWindowTitle(_translate("notesWindow", "Adicionar Lembrete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    notesWindow = QtWidgets.QMainWindow()
    ui = Ui_notesWindow()
    ui.setupUi(notesWindow)
    notesWindow.show()
    sys.exit(app.exec_())
