# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\deleteWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteWindow(object):
    def setupUi(self, deleteWindow):
        deleteWindow.setObjectName("deleteWindow")
        deleteWindow.resize(464, 641)
        deleteWindow.setMinimumSize(QtCore.QSize(464, 641))
        deleteWindow.setMaximumSize(QtCore.QSize(464, 641))
        deleteWindow.setStyleSheet("background-color: rgb(244, 232, 157);")
        self.centralwidget = QtWidgets.QWidget(deleteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(20, 540, 121, 81))
        self.leftButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leftButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: rgb(182, 182, 182);\n"
"}\n"
"")
        self.leftButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftButton.setIcon(icon)
        self.leftButton.setIconSize(QtCore.QSize(70, 70))
        self.leftButton.setObjectName("leftButton")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(170, 540, 121, 81))
        self.okButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.okButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(150, 193, 109);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(169, 225, 109);\n"
"}")
        self.okButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/okay.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon1)
        self.okButton.setIconSize(QtCore.QSize(30, 30))
        self.okButton.setObjectName("okButton")
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(320, 540, 121, 81))
        self.rightButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rightButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: rgb(182, 182, 182);\n"
"}\n"
"")
        self.rightButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/proximapag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButton.setIcon(icon2)
        self.rightButton.setIconSize(QtCore.QSize(80, 80))
        self.rightButton.setObjectName("rightButton")
        self.noteButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.noteButton1.setGeometry(QtCore.QRect(20, 20, 421, 161))
        self.noteButton1.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
)
        self.noteButton1.setObjectName("noteButton1")
        self.noteButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.noteButton2.setGeometry(QtCore.QRect(20, 190, 421, 161))
        self.noteButton2.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
)
        self.noteButton2.setObjectName("noteButton2")
        self.noteButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.noteButton3.setGeometry(QtCore.QRect(20, 360, 421, 161))
        self.noteButton3.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
)
        self.noteButton3.setObjectName("noteButton3")
        deleteWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(deleteWindow)
        self.okButton.clicked.connect(deleteWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(deleteWindow)

    def retranslateUi(self, deleteWindow):
        _translate = QtCore.QCoreApplication.translate
        deleteWindow.setWindowTitle(_translate("deleteWindow", "Excluir Lembrete"))
        self.noteButton1.setText(_translate("deleteWindow", "Vazio"))
        self.noteButton2.setText(_translate("deleteWindow", "Vazio"))
        self.noteButton3.setText(_translate("deleteWindow", "Vazio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteWindow = QtWidgets.QMainWindow()
    ui = Ui_deleteWindow()
    ui.setupUi(deleteWindow)
    deleteWindow.show()
    sys.exit(app.exec_())
